# Generated by Django 4.2.1 on 2023-06-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100, null=True)),
                ('marrital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('prefer not to say', 'prefer not to say')], max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.agent')),
            ],
        ),
    ]
